---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  aqua: ./tasks/aqua.task.yml
  format: ./tasks/format.task.yml
  reviewdog: ./tasks/reviewdog.task.yml

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    aliases: [all]
    cmds:
    - task: aqua
    - task: format
    - task: reviewdog
