---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  tool: ./tasks/tool.task.yml
  setup: ./tasks/setup.task.yml
  format: ./tasks/format.task.yml
  reviewdog: ./tasks/reviewdog.task.yml
  test: ./tasks/test.task.yml
  build: ./tasks/build.task.yml
  release: ./tasks/release.task.yml

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    aliases: [all]
    cmds:
    - task: tool
    - task: format
    - task: reviewdog
    - task: test
    - task: build
