---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  PROJNAME:
    sh: cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].name'
  # default profile
  PROFILE: '{{env "BUILD_PROFILE" | default "debug"}}'
  # default target
  TARGET: '{{env "BUILD_TARGET" | default "x86_64-unknown-linux-gnu"}}'

includes:
  tool:
    taskfile: tool.task.yml
    internal: true

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    cmds:
    - task: build
    - task: sha256sum

  build:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    label: build:{{.PROFILE}}:{{.TARGET}}
    deps:
    - task: tool:aqua:tag:build
    - task: tool:rustup:target:{{.TARGET}}
    sources:
    - 'Cargo.toml'
    - 'Cargo.lock'
    - 'src/**/*.rs'
    generates:
    - target/{{.TARGET}}/{{.PROFILE}}/{{.PROJNAME}}
    - dist/{{.PROJNAME}}-{{.PROFILE}}-{{.TARGET}}
    vars:
      PROFILE_ARG: '{{if eq .PROFILE "release"}}--release{{end}}'
      TARGET_ARG: '--target={{.TARGET}}{{if contains .TARGET "-linux-" }}.2.17{{end}}'
    cmds:
    - cargo zigbuild {{.PROFILE_ARG}} {{.TARGET_ARG}}
    - mkdir -p dist
    - cp target/{{.TARGET}}/{{.PROFILE}}/{{.PROJNAME}} dist/{{.PROJNAME}}-{{.PROFILE}}-{{.TARGET}}

  sha256sum:
    desc: '{{.TASK}}'
    label: sha256sum:{{.PROFILE}}:{{.TARGET}}
    dir: '{{.ROOT_DIR}}/dist'
    deps:
    - task: tool:aqua:tag:coreutils
    - task: build
      vars:
        PROFILE: '{{.PROFILE}}'
        TARGET: '{{.TARGET}}'
    vars:
      ARTIFACT: '{{.PROJNAME}}-{{.PROFILE}}-{{.TARGET}}'
    sources:
    - '{{.ARTIFACT}}'
    generates:
    - '{{.ARTIFACT}}.sha256sum'
    cmds:
    - coreutils sha256sum "{{.ARTIFACT}}" > "{{.ARTIFACT}}.sha256sum"

  cosign:
    desc: '{{.TASK}}'
    label: cosign:{{.PROFILE}}:{{.TARGET}}
    dir: '{{.ROOT_DIR}}/dist'
    deps:
    - task: tool:aqua:tag:cosign
    - task: build
      vars:
        PROFILE: '{{.PROFILE}}'
        TARGET: '{{.TARGET}}'
    vars:
      ARTIFACT: '{{.PROJNAME}}-{{.PROFILE}}-{{.TARGET}}'
    sources:
    - '{{.ARTIFACT}}'
    generates:
    - '{{.ARTIFACT}}.cert'
    - '{{.ARTIFACT}}.sig'
    cmds:
    - >-
      cosign sign-blob {{.ARTIFACT}}
      -y
      --output-certificate {{.ARTIFACT}}.cert
      --output-signature {{.ARTIFACT}}.sig
