---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  tool:
    taskfile: tool.task.yml
    internal: true

tasks:
  test:
    desc: '{{.TASK}}'
    silent: true
    deps:
    - task: tool:aqua:tag:rustup
    - task: tool:cargo:fetch
