---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  tool:
    taskfile: tool.task.yml
    internal: true

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    cmds:
    - task: test

  test:
    desc: '{{.TASK}}'
    label: test:workspace
    dir: '{{.ROOT_DIR}}'
    deps:
    - task: tool:aqua:tag:build
    sources:
    - 'Cargo.toml'
    - 'Cargo.lock'
    - 'src/**/*.rs'
    - 'tests/**/*.rs'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - cargo test --workspace
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
