//! resolv.conf lifecycle within a rootfs.
//!
//! [`RootfsResolvConf`] is an RAII guard that gives provisioning a working
//! `/etc/resolv.conf` and puts back whatever was there when it is done.

use std::sync::Arc;

use anyhow::Result;
use camino::{Utf8Path, Utf8PathBuf};
use tracing::info;

use crate::config::ResolvConfConfig;
use crate::error::RsdebstrapError;
use crate::pipeline::Provisioned;
use crate::rootfs::{RelPath, RootfsOps, TakenEntry};

/// Generates resolv.conf content from explicit configuration.
pub(crate) fn generate_resolv_conf(config: &ResolvConfConfig) -> String {
    let mut lines = Vec::new();
    lines.push("# Generated by rsdebstrap".to_string());
    if !config.search.is_empty() {
        lines.push(format!("search {}", config.search.join(" ")));
    }
    for ns in &config.name_servers {
        lines.push(format!("nameserver {}", ns));
    }
    lines.join("\n") + "\n"
}

/// Evidence that the rootfs's own resolv.conf is back in place.
///
/// [`Pipeline::run_assemble`](crate::pipeline::Pipeline::run_assemble) requires
/// one, and only this module can produce one. The restore has to land between
/// provisioning and assembly — an assemble `resolv_conf` task installs the
/// permanent `/etc/resolv.conf`, and a restore running afterwards would
/// overwrite it — so the orchestration is not free to reorder the two.
#[must_use]
#[derive(Debug)]
pub struct Restored(());

impl Restored {
    /// For a run with no prepare guard, where nothing was ever detached.
    ///
    /// The only way to obtain a `Restored` without restoring anything, and it
    /// still requires having provisioned first.
    pub(crate) fn nothing_was_detached(_provisioned: Provisioned) -> Self {
        Self(())
    }
}

/// The entry this guard replaces and restores.
fn resolv_conf_path() -> RelPath {
    RelPath::parse("/etc/resolv.conf").expect("literal path is valid")
}

/// RAII guard for resolv.conf within a rootfs.
///
/// Detaches the rootfs's own `/etc/resolv.conf` on setup, installs a temporary
/// one so provisioning can resolve names, and restores the original on teardown.
/// `Drop` retries the restore if the caller never did.
///
/// The original is held in memory as a [`TakenEntry`] rather
/// than moved to a backup path; that type documents why.
pub struct RootfsResolvConf {
    ops: Arc<dyn RootfsOps>,
    config: Option<ResolvConfConfig>,
    host_resolv_conf: Utf8PathBuf,
    /// For log lines only.
    rootfs: Utf8PathBuf,
    /// What setup detached, if anything was there.
    original: Option<TakenEntry>,
    active: bool,
    dry_run: bool,
    torn_down: bool,
}

impl RootfsResolvConf {
    /// Creates a guard over `rootfs`. If `config` is `None`, setup and teardown
    /// are no-ops.
    pub fn new(
        rootfs: &Utf8Path,
        config: Option<ResolvConfConfig>,
        host_resolv_conf: &Utf8Path,
        ops: Arc<dyn RootfsOps>,
        dry_run: bool,
    ) -> Self {
        Self {
            ops,
            config,
            host_resolv_conf: host_resolv_conf.to_owned(),
            rootfs: rootfs.to_owned(),
            original: None,
            active: false,
            dry_run,
            torn_down: false,
        }
    }

    /// Detaches the existing resolv.conf and installs the configured one.
    ///
    /// # Errors
    ///
    /// Returns an error if the entry cannot be detached or the replacement
    /// cannot be written. On a write failure the detached entry is put back
    /// before returning, so a failed setup leaves the rootfs as it was found.
    pub fn setup(&mut self) -> Result<()> {
        let Some(config) = &self.config else {
            return Ok(());
        };

        if self.dry_run {
            info!("would set up resolv.conf in {}", self.rootfs);
            return Ok(());
        }

        let path = resolv_conf_path();
        let original = self.ops.take(&path)?;

        // Read the host's copy here rather than in `RootfsOps`: the ops may be served by
        // the privileged helper, and there is no reason for root to be the one resolving a
        // host path. What crosses the boundary is bytes.
        let installed = if config.copy {
            match std::fs::read(&self.host_resolv_conf) {
                Ok(content) => self.ops.write_file(&path, &content, 0o644),
                Err(e) => {
                    Err(RsdebstrapError::io(format!("failed to read {}", self.host_resolv_conf), e))
                }
            }
        } else {
            self.ops
                .write_file(&path, generate_resolv_conf(config).as_bytes(), 0o644)
        };

        if let Err(write_err) = installed {
            if let Some(entry) = &original
                && let Err(rollback_err) = self.ops.put_back(&path, entry)
            {
                tracing::error!(
                    "failed to restore the original resolv.conf after a failed setup: {}",
                    rollback_err
                );
            }
            return Err(write_err.into());
        }

        info!("set up resolv.conf in {}", self.rootfs);
        self.original = original;
        self.active = true;
        Ok(())
    }

    /// Restores the entry setup detached, in exchange for the token
    /// [`Pipeline::run_assemble`](crate::pipeline::Pipeline::run_assemble)
    /// requires.
    ///
    /// Taking [`Provisioned`] and yielding [`Restored`] is what places this
    /// between provisioning and assembly: assembly cannot be called without the
    /// token, and the token cannot exist before this returns.
    ///
    /// # Errors
    ///
    /// Returns an error if the original cannot be written back. `Drop` retries
    /// the restore in that case.
    pub fn restore(&mut self, _provisioned: Provisioned) -> Result<Restored> {
        self.teardown()?;
        Ok(Restored(()))
    }

    /// Restores the entry setup detached. Idempotent after a successful call.
    pub fn teardown(&mut self) -> Result<()> {
        if !self.active || self.torn_down {
            return Ok(());
        }

        let path = resolv_conf_path();
        match &self.original {
            // Overwrites the temporary resolv.conf in one atomic rename; no
            // window exists in which the rootfs has no resolv.conf at all.
            Some(entry) => self.ops.put_back(&path, entry)?,
            None => self.ops.remove(&path)?,
        }

        info!("restored resolv.conf in {}", self.rootfs);
        self.torn_down = true;
        Ok(())
    }

    /// Gives up ownership of the original without restoring it.
    ///
    /// Used when a later phase has taken responsibility for the final
    /// `/etc/resolv.conf`, so the `Drop` backstop must not overwrite it.
    pub fn disarm(&mut self) {
        self.torn_down = true;
    }
}

impl Drop for RootfsResolvConf {
    fn drop(&mut self) {
        if self.active
            && !self.torn_down
            && let Err(e) = self.teardown()
        {
            tracing::error!(
                "failed to restore resolv.conf during cleanup: {}. \
                {}/etc/resolv.conf may still hold the temporary configuration",
                e,
                self.rootfs
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rootfs::LocalRootfsOps;
    use std::fs;

    fn rootfs_with_etc() -> (tempfile::TempDir, Utf8PathBuf) {
        let temp = tempfile::tempdir().unwrap();
        let rootfs = Utf8PathBuf::from_path_buf(temp.path().to_path_buf()).unwrap();
        fs::create_dir_all(rootfs.join("etc")).unwrap();
        (temp, rootfs)
    }

    fn guard(rootfs: &Utf8Path, config: Option<ResolvConfConfig>) -> RootfsResolvConf {
        let ops = Arc::new(LocalRootfsOps::open(rootfs).unwrap());
        RootfsResolvConf::new(rootfs, config, Utf8Path::new("/etc/resolv.conf"), ops, false)
    }

    fn generated(name_servers: &[&str]) -> ResolvConfConfig {
        ResolvConfConfig {
            copy: false,
            name_servers: name_servers.iter().map(|s| s.parse().unwrap()).collect(),
            search: vec![],
        }
    }

    fn resolv_conf(rootfs: &Utf8Path) -> Utf8PathBuf {
        rootfs.join("etc/resolv.conf")
    }

    // Fails the *first* write only, so setup's install fails while the rollback
    // that follows it succeeds. Failing every write would also break the
    // rollback and the test could not tell the two apart.
    struct FailFirstWrite {
        inner: LocalRootfsOps,
        failed: std::sync::atomic::AtomicBool,
    }

    impl FailFirstWrite {
        fn new(inner: LocalRootfsOps) -> Self {
            Self {
                inner,
                failed: std::sync::atomic::AtomicBool::new(false),
            }
        }
    }

    impl RootfsOps for FailFirstWrite {
        fn write_file(
            &self,
            path: &RelPath,
            content: &[u8],
            mode: u32,
        ) -> std::result::Result<(), crate::error::RsdebstrapError> {
            if !self.failed.swap(true, std::sync::atomic::Ordering::SeqCst) {
                return Err(crate::error::RsdebstrapError::Isolation("write refused".into()));
            }
            self.inner.write_file(path, content, mode)
        }
        fn write_symlink(
            &self,
            path: &RelPath,
            target: &str,
        ) -> std::result::Result<(), crate::error::RsdebstrapError> {
            self.inner.write_symlink(path, target)
        }

        fn remove(&self, path: &RelPath) -> std::result::Result<(), crate::error::RsdebstrapError> {
            self.inner.remove(path)
        }

        fn take(
            &self,
            path: &RelPath,
        ) -> std::result::Result<Option<TakenEntry>, crate::error::RsdebstrapError> {
            self.inner.take(path)
        }
    }

    #[test]
    fn generate_nameservers_only() {
        let config = ResolvConfConfig {
            copy: false,
            name_servers: vec!["8.8.8.8".parse().unwrap(), "8.8.4.4".parse().unwrap()],
            search: vec![],
        };
        let content = generate_resolv_conf(&config);
        assert_eq!(content, "# Generated by rsdebstrap\nnameserver 8.8.8.8\nnameserver 8.8.4.4\n");
    }

    #[test]
    fn generate_nameservers_and_search() {
        let config = ResolvConfConfig {
            copy: false,
            name_servers: vec!["127.0.0.1".parse().unwrap()],
            search: vec!["example.com".to_string(), "corp.example.com".to_string()],
        };
        let content = generate_resolv_conf(&config);
        assert_eq!(
            content,
            "# Generated by rsdebstrap\nsearch example.com corp.example.com\nnameserver 127.0.0.1\n"
        );
    }

    #[test]
    fn generate_search_only() {
        let config = ResolvConfConfig {
            copy: false,
            name_servers: vec![],
            search: vec!["example.com".to_string()],
        };
        let content = generate_resolv_conf(&config);
        assert_eq!(content, "# Generated by rsdebstrap\nsearch example.com\n");
    }

    #[test]
    fn generate_ipv6_nameserver() {
        let config = ResolvConfConfig {
            copy: false,
            name_servers: vec!["::1".parse().unwrap()],
            search: vec![],
        };
        let content = generate_resolv_conf(&config);
        assert_eq!(content, "# Generated by rsdebstrap\nnameserver ::1\n");
    }

    #[test]
    fn no_config_leaves_the_rootfs_untouched() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let mut g = guard(&rootfs, None);
        g.setup().unwrap();
        g.teardown().unwrap();

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    #[test]
    fn dry_run_leaves_the_rootfs_untouched() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let ops = Arc::new(LocalRootfsOps::open(&rootfs).unwrap());
        let mut g = RootfsResolvConf::new(
            &rootfs,
            Some(generated(&["8.8.8.8"])),
            Utf8Path::new("/etc/resolv.conf"),
            ops,
            true,
        );
        g.setup().unwrap();

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    #[test]
    fn setup_installs_the_generated_config() {
        let (_temp, rootfs) = rootfs_with_etc();
        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));

        g.setup().unwrap();

        assert_eq!(
            fs::read_to_string(resolv_conf(&rootfs)).unwrap(),
            "# Generated by rsdebstrap\nnameserver 1.1.1.1\n"
        );
    }

    #[test]
    fn setup_copies_the_host_file_in_copy_mode() {
        let (_temp, rootfs) = rootfs_with_etc();
        let host = rootfs.join("host-resolv.conf");
        fs::write(&host, "nameserver 10.0.0.1\n").unwrap();

        let ops = Arc::new(LocalRootfsOps::open(&rootfs).unwrap());
        let config = ResolvConfConfig {
            copy: true,
            name_servers: vec![],
            search: vec![],
        };
        let mut g = RootfsResolvConf::new(&rootfs, Some(config), &host, ops, false);
        g.setup().unwrap();

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "nameserver 10.0.0.1\n");
    }

    #[test]
    fn teardown_restores_a_regular_file_original() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        g.setup().unwrap();
        assert_ne!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");

        g.teardown().unwrap();
        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    // A fresh systemd rootfs ships /etc/resolv.conf as a symlink into /run whose
    // target does not exist yet. The old guard checked for its backup with
    // `try_exists()`, which follows the link and reports a dangling one as
    // absent, so the restore was skipped and the original was lost. Nothing is
    // stat'd through a link now: the entry is held as a symlink value.
    #[test]
    fn teardown_restores_a_dangling_symlink_original() {
        let (_temp, rootfs) = rootfs_with_etc();
        let target = "../run/systemd/resolve/stub-resolv.conf";
        std::os::unix::fs::symlink(target, resolv_conf(&rootfs)).unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        g.setup().unwrap();
        assert!(
            fs::symlink_metadata(resolv_conf(&rootfs))
                .unwrap()
                .file_type()
                .is_file()
        );

        g.teardown().unwrap();

        let restored = fs::symlink_metadata(resolv_conf(&rootfs)).unwrap();
        assert!(restored.file_type().is_symlink(), "original was not restored as a symlink");
        assert_eq!(
            fs::read_link(resolv_conf(&rootfs))
                .unwrap()
                .to_str()
                .unwrap(),
            target
        );
    }

    #[test]
    fn teardown_removes_the_temporary_file_when_there_was_no_original() {
        let (_temp, rootfs) = rootfs_with_etc();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        g.setup().unwrap();
        g.teardown().unwrap();

        assert!(!resolv_conf(&rootfs).exists());
    }

    #[test]
    fn a_failed_setup_puts_the_original_back() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let ops = Arc::new(FailFirstWrite::new(LocalRootfsOps::open(&rootfs).unwrap()));
        let mut g = RootfsResolvConf::new(
            &rootfs,
            Some(generated(&["1.1.1.1"])),
            Utf8Path::new("/etc/resolv.conf"),
            ops,
            false,
        );

        assert!(g.setup().is_err());
        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    #[test]
    fn setup_refuses_a_symlinked_etc() {
        let (_temp, rootfs) = rootfs_with_etc();
        let outside = rootfs.join("outside");
        fs::create_dir(&outside).unwrap();
        fs::remove_dir(rootfs.join("etc")).unwrap();
        std::os::unix::fs::symlink(&outside, rootfs.join("etc")).unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        let err = g.setup().unwrap_err();

        assert!(err.to_string().contains("symlink"), "unexpected error: {err}");
        assert!(!outside.join("resolv.conf").exists(), "wrote through the symlink");
    }

    #[test]
    fn setup_errors_when_etc_is_missing() {
        let temp = tempfile::tempdir().unwrap();
        let rootfs = Utf8PathBuf::from_path_buf(temp.path().to_path_buf()).unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        assert!(g.setup().is_err());
    }

    #[test]
    fn drop_restores_the_original_when_teardown_was_not_called() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        {
            let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
            g.setup().unwrap();
        }

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    // Disarming hands the final state to a later phase, so the Drop backstop
    // must not overwrite what that phase installed.
    #[test]
    fn drop_does_nothing_after_disarm() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        {
            let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
            g.setup().unwrap();
            g.disarm();
        }

        assert_eq!(
            fs::read_to_string(resolv_conf(&rootfs)).unwrap(),
            "# Generated by rsdebstrap\nnameserver 1.1.1.1\n"
        );
    }

    #[test]
    fn teardown_is_idempotent() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        g.setup().unwrap();
        g.teardown().unwrap();
        fs::write(resolv_conf(&rootfs), "written after teardown\n").unwrap();
        g.teardown().unwrap();

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "written after teardown\n");
    }
}
