//! resolv.conf lifecycle within a rootfs.
//!
//! [`RootfsResolvConf`] is an RAII guard that gives provisioning a working
//! `/etc/resolv.conf` and puts back whatever was there when it is done.

use std::io::Read;
use std::marker::PhantomData;
use std::sync::Arc;

use anyhow::Result;
use camino::{Utf8Path, Utf8PathBuf};
use tracing::info;

use crate::config::{MountEntry, ResolvConfConfig};
use crate::error::RsdebstrapError;
use crate::isolation::mount::Mounted;
use crate::pipeline::Provisioned;
use crate::rootfs::{FileMode, RelPath, RootfsOps, TakenEntry};

/// Refuses to copy a host resolver config larger than this.
///
/// A resolv.conf is a handful of lines; anything near this is not the file the profile
/// meant. The bound matters because the bytes are buffered rather than streamed -- with the
/// privileged helper serving the run they cross the boundary base64 inside JSON -- so
/// "however large the host file happens to be" is not an answer this can give.
const MAX_HOST_RESOLV_CONF_SIZE: u64 = 1 << 20;

/// Generates resolv.conf content from explicit configuration.
pub(crate) fn generate_resolv_conf(config: &ResolvConfConfig) -> String {
    let mut lines = Vec::new();
    lines.push("# Generated by rsdebstrap".to_string());
    if !config.search.is_empty() {
        lines.push(format!("search {}", config.search.join(" ")));
    }
    for ns in &config.name_servers {
        lines.push(format!("nameserver {}", ns));
    }
    lines.join("\n") + "\n"
}

/// Evidence that the prepare phase's guards are in place.
///
/// [`Pipeline::run_prepare_and_provision`](crate::pipeline::Pipeline::run_prepare_and_provision)
/// requires one, so provisioning cannot be entered by a caller that skipped them. A prepare
/// task has nothing to run — what `prepare.mount` and `prepare.resolv_conf` declare is
/// carried by RAII guards that bracket provisioning — and iterating the phase would
/// otherwise report those tasks as done while a run that never armed the guards provisioned
/// without the mounts or the DNS the profile asked for.
///
/// Like [`Mounted`], it borrows the guards rather than standing for them: it carries the
/// [`Mounted`] borrow forward and adds its own, so neither guard can be torn down or dropped
/// while it is alive. A token that outlived them would say the prepare phase *had been* set
/// up, which is not what provisioning needs to know.
///
/// It says the guards ran, not that they were built from the same `prepare` config as the
/// pipeline being provisioned; binding that would mean constructing them from it. What it
/// rules out is the case with no guards at all.
#[must_use]
#[derive(Debug)]
pub(crate) struct Prepared<'a> {
    rootfs: &'a Utf8Path,
    mounts: &'a [MountEntry],
    resolv_conf: Option<&'a ResolvConfConfig>,
    guard: PhantomData<&'a RootfsResolvConf>,
}

impl<'a> Prepared<'a> {
    /// For a pipeline with no prepare phase, where there is nothing for a guard to do.
    ///
    /// The only way to obtain a `Prepared` without arming one, and
    /// [`Pipeline::run`](crate::pipeline::Pipeline::run) — the one caller — earns it by
    /// refusing a pipeline that declares any prepare task. It still names the rootfs, so it
    /// cannot be presented for a different one.
    pub(crate) fn nothing_to_prepare(rootfs: &'a Utf8Path) -> Self {
        Self {
            rootfs,
            mounts: &[],
            resolv_conf: None,
            guard: PhantomData,
        }
    }

    /// The rootfs both guards were built for.
    pub(crate) fn rootfs(&self) -> &'a Utf8Path {
        self.rootfs
    }

    /// The mount entries the mount guard was built for.
    pub(crate) fn mounts(&self) -> &'a [MountEntry] {
        self.mounts
    }

    /// The resolver config the resolv.conf guard was built for, if any.
    pub(crate) fn resolv_conf(&self) -> Option<&'a ResolvConfConfig> {
        self.resolv_conf
    }
}

/// Evidence that the rootfs's own resolv.conf is back in place.
///
/// [`Pipeline::run_assemble`](crate::pipeline::Pipeline::run_assemble) requires
/// one, and only this module can produce one. The restore has to land between
/// provisioning and assembly — an assemble `resolv_conf` task installs the
/// permanent `/etc/resolv.conf`, and a restore running afterwards would
/// overwrite it — so the orchestration is not free to reorder the two.
#[must_use]
#[derive(Debug)]
pub(crate) struct Restored(());

impl Restored {
    /// For a run with no prepare guard, where nothing was ever detached.
    ///
    /// The only way to obtain a `Restored` without restoring anything, and it
    /// still requires having provisioned first.
    pub(crate) fn nothing_was_detached(_provisioned: Provisioned) -> Self {
        Self(())
    }
}

/// The entry this guard replaces and restores.
fn resolv_conf_path() -> RelPath {
    RelPath::parse("/etc/resolv.conf").expect("literal path is valid")
}

/// RAII guard for resolv.conf within a rootfs.
///
/// Detaches the rootfs's own `/etc/resolv.conf` on setup, installs a temporary
/// one so provisioning can resolve names, and restores the original on teardown.
/// `Drop` retries the restore if the caller never did.
///
/// The original is held in memory as a [`TakenEntry`] rather
/// than moved to a backup path; that type documents why.
pub(crate) struct RootfsResolvConf {
    ops: Arc<dyn RootfsOps>,
    config: Option<ResolvConfConfig>,
    host_resolv_conf: Utf8PathBuf,
    /// For log lines only.
    rootfs: Utf8PathBuf,
    /// What setup detached, if anything was there.
    original: Option<TakenEntry>,
    active: bool,
    dry_run: bool,
    torn_down: bool,
}

impl RootfsResolvConf {
    /// Creates a guard over `rootfs`. If `config` is `None`, setup and teardown
    /// are no-ops.
    pub(crate) fn new(
        rootfs: &Utf8Path,
        config: Option<ResolvConfConfig>,
        host_resolv_conf: &Utf8Path,
        ops: Arc<dyn RootfsOps>,
        dry_run: bool,
    ) -> Self {
        Self {
            ops,
            config,
            host_resolv_conf: host_resolv_conf.to_owned(),
            rootfs: rootfs.to_owned(),
            original: None,
            active: false,
            dry_run,
            torn_down: false,
        }
    }

    /// Detaches the existing resolv.conf and installs the configured one.
    ///
    /// # Errors
    ///
    /// Returns an error if the entry cannot be detached or the replacement
    /// cannot be written. On a write failure the detached entry is put back
    /// before returning, so a failed setup leaves the rootfs as it was found.
    /// If that rollback fails too, the returned error says so and the guard
    /// stays armed, leaving the retry to `Drop`.
    pub(crate) fn setup<'a>(&'a mut self, mounted: Mounted<'a>) -> Result<Prepared<'a>> {
        // Two guards for two different rootfs directories would otherwise combine into one
        // token naming neither.
        if mounted.rootfs() != self.rootfs {
            return Err(RsdebstrapError::Isolation(format!(
                "the mounts were established for {} but this guard is over {}",
                mounted.rootfs(),
                self.rootfs
            ))
            .into());
        }
        let prepared = Prepared {
            rootfs: mounted.rootfs(),
            mounts: mounted.entries(),
            resolv_conf: self.config.as_ref(),
            guard: PhantomData,
        };

        // The detached original exists only in `self.original`. A second `take` would find
        // the temporary this guard installed, overwrite the original with it, and leave
        // teardown restoring the temporary as if it were the rootfs's own -- losing the
        // real one for good, with nothing left to notice it by.
        if self.active || self.torn_down {
            return Err(RsdebstrapError::Isolation(
                "setup() called on an already-used RootfsResolvConf".to_string(),
            )
            .into());
        }

        let Some(config) = &self.config else {
            return Ok(prepared);
        };

        if self.dry_run {
            info!("would set up resolv.conf in {}", self.rootfs);
            return Ok(prepared);
        }

        let path = resolv_conf_path();
        // Hand the detached entry to the guard before installing the replacement. `take`
        // unlinks it, so from here the only copy is this one in memory; if the install
        // below fails *and* the rollback fails too, `Drop` is the last thing that can put
        // it back, and it only runs for a guard that is armed.
        self.original = self.ops.take(&path)?;
        self.active = self.original.is_some();

        // Read the host's copy here rather than in `RootfsOps`: the ops may be served by
        // the privileged helper, and there is no reason for root to be the one resolving a
        // host path. What crosses the boundary is bytes.
        let installed = if config.copy {
            match self.read_host_resolv_conf() {
                Ok(content) => self.ops.write_file(&path, &content, FileMode::new(0o644)),
                Err(e) => Err(e),
            }
        } else {
            self.ops.write_file(
                &path,
                generate_resolv_conf(config).as_bytes(),
                FileMode::new(0o644),
            )
        };

        if let Err(write_err) = installed {
            let Some(entry) = &self.original else {
                // Nothing was detached, and the failed write left nothing behind, so the
                // rootfs is already as it was found.
                return Err(write_err.into());
            };
            if let Err(rollback_err) = self.ops.put_back(&path, entry) {
                // The rootfs now has no resolv.conf and the original exists only in this
                // guard. Say so in the error rather than only in a log line: the caller
                // drops the guard on the way out, and that `Drop` is the retry.
                return Err(anyhow::Error::new(write_err).context(format!(
                    "the original {}/etc/resolv.conf could not be put back either ({}); \
                    it is detached and held in memory until cleanup retries the restore",
                    self.rootfs, rollback_err
                )));
            }
            self.original = None;
            self.active = false;
            return Err(write_err.into());
        }

        info!("set up resolv.conf in {}", self.rootfs);
        self.active = true;
        Ok(prepared)
    }

    /// Restores the entry setup detached, in exchange for the token
    /// [`Pipeline::run_assemble`](crate::pipeline::Pipeline::run_assemble)
    /// requires.
    ///
    /// Taking [`Provisioned`] and yielding [`Restored`] is what places this
    /// between provisioning and assembly: assembly cannot be called without the
    /// token, and the token cannot exist before this returns.
    ///
    /// It also asks for [`Mounted`] again, rather than one carried from setup. A
    /// `prepare.mount` may sit over the directory this restores into -- `/etc` is a
    /// plausible target -- in which case setup replaced the entry on the mounted
    /// filesystem, and restoring after the unmount would put the original on the
    /// directory underneath while leaving the temporary on the mounted one. The token
    /// cannot be carried here: a borrow taken at
    /// [`RootfsMounts::mount`](crate::isolation::mount::RootfsMounts::mount) would still be
    /// alive at the unmount that has to follow this. Asked for again through
    /// [`still_mounted`](crate::isolation::mount::RootfsMounts::still_mounted), it also
    /// rules out the guard having been dropped, which no borrow reaching this far could.
    ///
    /// # Errors
    ///
    /// Returns an error if the original cannot be written back. `Drop` retries
    /// the restore in that case.
    pub(crate) fn restore(
        &mut self,
        _provisioned: Provisioned,
        mounted: Mounted<'_>,
    ) -> Result<Restored> {
        // The same comparison `setup` makes. Asking for a `Mounted` is only worth anything
        // if it is evidence about *these* mounts: a token from a second guard -- an empty
        // one over an unrelated directory hands one out for free -- would otherwise satisfy
        // the window this restore has to land inside.
        if mounted.rootfs() != self.rootfs {
            return Err(RsdebstrapError::Isolation(format!(
                "the mounts still in place are for {} but this guard is over {}",
                mounted.rootfs(),
                self.rootfs
            ))
            .into());
        }
        self.teardown()?;
        Ok(Restored(()))
    }

    /// Restores the entry setup detached. Idempotent after a successful call.
    pub(crate) fn teardown(&mut self) -> Result<()> {
        if !self.active || self.torn_down {
            return Ok(());
        }

        let path = resolv_conf_path();
        match &self.original {
            // Overwrites the temporary resolv.conf in one atomic rename; no
            // window exists in which the rootfs has no resolv.conf at all.
            Some(entry) => self.ops.put_back(&path, entry)?,
            None => self.ops.remove(&path)?,
        }

        info!("restored resolv.conf in {}", self.rootfs);
        self.torn_down = true;
        Ok(())
    }
}

impl RootfsResolvConf {
    /// Reads the host's resolver config for `copy` mode.
    ///
    /// Symlinks are followed deliberately, unlike every other host read here: on a
    /// systemd host `/etc/resolv.conf` *is* a symlink to the stub, and the bytes behind it
    /// are the point.
    fn read_host_resolv_conf(&self) -> std::result::Result<Vec<u8>, RsdebstrapError> {
        let io_error = |e: std::io::Error| {
            RsdebstrapError::io(format!("failed to read {}", self.host_resolv_conf), e)
        };
        let file = std::fs::File::open(&self.host_resolv_conf).map_err(io_error)?;
        let size = file.metadata().map_err(io_error)?.len();
        if size > MAX_HOST_RESOLV_CONF_SIZE {
            return Err(RsdebstrapError::Validation(format!(
                "{} is {} bytes, refusing to copy a resolver config over {} bytes",
                self.host_resolv_conf, size, MAX_HOST_RESOLV_CONF_SIZE
            )));
        }

        // Bounded on top of the size just read, because the host file can be rewritten --
        // by `resolvconf`, or by a DHCP client -- while this is reading it.
        let mut content = Vec::new();
        file.take(MAX_HOST_RESOLV_CONF_SIZE + 1)
            .read_to_end(&mut content)
            .map_err(io_error)?;
        if content.len() as u64 > MAX_HOST_RESOLV_CONF_SIZE {
            return Err(RsdebstrapError::Validation(format!(
                "{} grew past {} bytes while it was being read, refusing to copy it",
                self.host_resolv_conf, MAX_HOST_RESOLV_CONF_SIZE
            )));
        }
        Ok(content)
    }
}

impl Drop for RootfsResolvConf {
    fn drop(&mut self) {
        if self.active
            && !self.torn_down
            && let Err(e) = self.teardown()
        {
            tracing::error!(
                "failed to restore resolv.conf during cleanup: {}. \
                {}/etc/resolv.conf may still hold the temporary configuration",
                e,
                self.rootfs
            );
        }
    }
}

// Deliberately omits `original`: a `TakenEntry::File` holds the detached file's bytes,
// and dumping them says nothing about the guard. What a reader wants is whether setup
// ran and whether the restore is still owed.
impl std::fmt::Debug for RootfsResolvConf {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RootfsResolvConf")
            .field("rootfs", &self.rootfs)
            .field("active", &self.active)
            .field("detached", &self.original.is_some())
            .field("dry_run", &self.dry_run)
            .field("torn_down", &self.torn_down)
            .finish_non_exhaustive()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rootfs::LocalRootfsOps;
    use std::fs;

    fn rootfs_with_etc() -> (tempfile::TempDir, Utf8PathBuf) {
        let temp = tempfile::tempdir().unwrap();
        let rootfs = Utf8PathBuf::from_path_buf(temp.path().to_path_buf()).unwrap();
        fs::create_dir_all(rootfs.join("etc")).unwrap();
        (temp, rootfs)
    }

    // The token `setup` requires. Produced by a real mount guard with no entries rather than
    // by a test-only constructor: `mount()` on an empty guard touches nothing and cannot
    // fail, so this is the evidence the guard actually hands out.
    // `Mounted` borrows the guard it came from, so no helper can hand one back -- which is
    // the point of the borrow. This runs the whole setup through a real mount guard with no
    // entries instead: `mount()` on one touches nothing and cannot fail, and there is no
    // `#[cfg(test)]` way around the mounts.
    fn setup_guard(g: &mut RootfsResolvConf) -> Result<()> {
        // Over the same rootfs as `g`: the token names what it is evidence about, and
        // `setup` refuses one armed over a different directory.
        let rootfs = g.rootfs.clone();
        let mut mounts = crate::isolation::mount::RootfsMounts::new(
            &rootfs,
            Vec::new(),
            Arc::new(crate::executor::RealCommandExecutor::new(true)),
            None,
        );
        let mounted = mounts.mount().expect("an empty mount guard mounts nothing");
        // The `Prepared` is what provisioning would consume; these tests are about the
        // guard's own effect on the rootfs, so it is dropped here.
        let _prepared = g.setup(mounted)?;
        Ok(())
    }

    fn guard(rootfs: &Utf8Path, config: Option<ResolvConfConfig>) -> RootfsResolvConf {
        let ops = Arc::new(LocalRootfsOps::open(rootfs).unwrap());
        RootfsResolvConf::new(rootfs, config, Utf8Path::new("/etc/resolv.conf"), ops, false)
    }

    fn generated(name_servers: &[&str]) -> ResolvConfConfig {
        ResolvConfConfig {
            copy: false,
            name_servers: name_servers.iter().map(|s| s.parse().unwrap()).collect(),
            search: vec![],
        }
    }

    fn resolv_conf(rootfs: &Utf8Path) -> Utf8PathBuf {
        rootfs.join("etc/resolv.conf")
    }

    // The `Debug` impl reports the guard's state, and the detached entry is not part of
    // it: `TakenEntry::File` carries the bytes of whatever was replaced, and a reader
    // asking about the guard is asking whether the restore is still owed, not what the
    // old file said. `detached` answers that in one bool.
    #[test]
    fn debug_reports_state_without_the_detached_content() {
        let (_tmp, rootfs) = rootfs_with_etc();
        let secret = "nameserver 198.51.100.99\n";
        fs::write(resolv_conf(&rootfs), secret).unwrap();

        let mut g = guard(&rootfs, Some(generated(&["192.0.2.1"])));
        setup_guard(&mut g).unwrap();
        let rendered = format!("{g:?}");

        assert!(rendered.contains("detached: true"), "state is missing: {rendered}");
        assert!(rendered.contains("active: true"), "state is missing: {rendered}");
        assert!(rendered.contains("torn_down: false"), "state is missing: {rendered}");
        // The bytes render as a decimal array, so look for the first few of them.
        let as_bytes = format!("{:?}", secret.as_bytes());
        let head = &as_bytes[..as_bytes.len() / 2];
        assert!(!rendered.contains(head), "the detached content leaked into Debug: {rendered}");
        assert!(rendered.ends_with(".. }"), "omitted fields are not marked: {rendered}");
    }

    // Fails the first `n` writes and then works. Setup writes twice on the failure
    // path — the install, then the rollback's `put_back` — and `Drop`'s retry is the
    // third, so the count is what separates "the install failed" from "the install and
    // the rollback both failed". Failing every write would collapse the two.
    struct FailFirstWrites {
        inner: LocalRootfsOps,
        remaining: std::sync::atomic::AtomicUsize,
    }

    impl FailFirstWrites {
        fn new(inner: LocalRootfsOps, n: usize) -> Self {
            Self {
                inner,
                remaining: std::sync::atomic::AtomicUsize::new(n),
            }
        }
    }

    impl RootfsOps for FailFirstWrites {
        fn write_file(
            &self,
            path: &RelPath,
            content: &[u8],
            mode: FileMode,
        ) -> std::result::Result<(), crate::error::RsdebstrapError> {
            if self
                .remaining
                .fetch_update(
                    std::sync::atomic::Ordering::SeqCst,
                    std::sync::atomic::Ordering::SeqCst,
                    |n| n.checked_sub(1),
                )
                .is_ok()
            {
                return Err(crate::error::RsdebstrapError::Isolation("write refused".into()));
            }
            self.inner.write_file(path, content, mode)
        }
        fn write_symlink(
            &self,
            path: &RelPath,
            target: &[u8],
        ) -> std::result::Result<(), crate::error::RsdebstrapError> {
            self.inner.write_symlink(path, target)
        }

        // Routed through this mock's own `write_file` rather than the inner ops, so a
        // restore counts against the failure budget the way the real one does.
        fn put_back(
            &self,
            path: &RelPath,
            entry: &crate::rootfs::TakenEntry,
        ) -> std::result::Result<(), crate::error::RsdebstrapError> {
            match entry {
                crate::rootfs::TakenEntry::File { content, mode, .. } => {
                    self.write_file(path, content, *mode)
                }
                crate::rootfs::TakenEntry::Symlink { target, .. } => {
                    self.write_symlink(path, target)
                }
            }
        }

        fn remove(&self, path: &RelPath) -> std::result::Result<(), crate::error::RsdebstrapError> {
            self.inner.remove(path)
        }

        fn take(
            &self,
            path: &RelPath,
        ) -> std::result::Result<Option<TakenEntry>, crate::error::RsdebstrapError> {
            self.inner.take(path)
        }
    }

    #[test]
    fn generate_nameservers_only() {
        let config = ResolvConfConfig {
            copy: false,
            name_servers: vec!["8.8.8.8".parse().unwrap(), "8.8.4.4".parse().unwrap()],
            search: vec![],
        };
        let content = generate_resolv_conf(&config);
        assert_eq!(content, "# Generated by rsdebstrap\nnameserver 8.8.8.8\nnameserver 8.8.4.4\n");
    }

    #[test]
    fn generate_nameservers_and_search() {
        let config = ResolvConfConfig {
            copy: false,
            name_servers: vec!["127.0.0.1".parse().unwrap()],
            search: vec!["example.com".to_string(), "corp.example.com".to_string()],
        };
        let content = generate_resolv_conf(&config);
        assert_eq!(
            content,
            "# Generated by rsdebstrap\nsearch example.com corp.example.com\nnameserver 127.0.0.1\n"
        );
    }

    #[test]
    fn generate_search_only() {
        let config = ResolvConfConfig {
            copy: false,
            name_servers: vec![],
            search: vec!["example.com".to_string()],
        };
        let content = generate_resolv_conf(&config);
        assert_eq!(content, "# Generated by rsdebstrap\nsearch example.com\n");
    }

    #[test]
    fn generate_ipv6_nameserver() {
        let config = ResolvConfConfig {
            copy: false,
            name_servers: vec!["::1".parse().unwrap()],
            search: vec![],
        };
        let content = generate_resolv_conf(&config);
        assert_eq!(content, "# Generated by rsdebstrap\nnameserver ::1\n");
    }

    #[test]
    fn no_config_leaves_the_rootfs_untouched() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let mut g = guard(&rootfs, None);
        setup_guard(&mut g).unwrap();
        g.teardown().unwrap();

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    // The original exists only in the guard's memory once setup has run, so a second setup
    // would `take` the temporary this one installed, overwrite the original with it, and
    // leave teardown restoring the temporary under the original's name. Nothing downstream
    // could tell: the file would be there, with plausible content.
    #[test]
    fn setup_refuses_to_run_twice_and_keeps_the_original() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        setup_guard(&mut g).unwrap();

        let err = setup_guard(&mut g)
            .expect_err("a second setup must not take the temporary it installed");
        assert!(err.to_string().contains("already-used"), "unexpected error: {err:#}");

        g.teardown().unwrap();
        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    // A guard that has been torn down has nothing left to restore, so a setup after it
    // would arm one whose `original` is empty while the rootfs holds a temporary.
    #[test]
    fn setup_refuses_to_run_after_teardown() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        setup_guard(&mut g).unwrap();
        g.teardown().unwrap();

        let err = setup_guard(&mut g).expect_err("a torn-down guard must not be armed again");
        assert!(err.to_string().contains("already-used"), "unexpected error: {err:#}");
        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    #[test]
    fn dry_run_leaves_the_rootfs_untouched() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let ops = Arc::new(LocalRootfsOps::open(&rootfs).unwrap());
        let mut g = RootfsResolvConf::new(
            &rootfs,
            Some(generated(&["8.8.8.8"])),
            Utf8Path::new("/etc/resolv.conf"),
            ops,
            true,
        );
        setup_guard(&mut g).unwrap();

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    #[test]
    fn setup_installs_the_generated_config() {
        let (_temp, rootfs) = rootfs_with_etc();
        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));

        setup_guard(&mut g).unwrap();

        assert_eq!(
            fs::read_to_string(resolv_conf(&rootfs)).unwrap(),
            "# Generated by rsdebstrap\nnameserver 1.1.1.1\n"
        );
    }

    #[test]
    fn setup_copies_the_host_file_in_copy_mode() {
        let (_temp, rootfs) = rootfs_with_etc();
        let host = rootfs.join("host-resolv.conf");
        fs::write(&host, "nameserver 10.0.0.1\n").unwrap();

        let ops = Arc::new(LocalRootfsOps::open(&rootfs).unwrap());
        let config = ResolvConfConfig {
            copy: true,
            name_servers: vec![],
            search: vec![],
        };
        let mut g = RootfsResolvConf::new(&rootfs, Some(config), &host, ops, false);
        setup_guard(&mut g).unwrap();

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "nameserver 10.0.0.1\n");
    }

    #[test]
    fn teardown_restores_a_regular_file_original() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        setup_guard(&mut g).unwrap();
        assert_ne!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");

        g.teardown().unwrap();
        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    // A fresh systemd rootfs ships /etc/resolv.conf as a symlink into /run whose
    // target does not exist yet. `try_exists()` follows the link and reports a
    // dangling one as absent, so nothing may be stat'd through a link to decide
    // whether there is an original to restore: the entry is held as a symlink value.
    #[test]
    fn teardown_restores_a_dangling_symlink_original() {
        let (_temp, rootfs) = rootfs_with_etc();
        let target = "../run/systemd/resolve/stub-resolv.conf";
        std::os::unix::fs::symlink(target, resolv_conf(&rootfs)).unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        setup_guard(&mut g).unwrap();
        assert!(
            fs::symlink_metadata(resolv_conf(&rootfs))
                .unwrap()
                .file_type()
                .is_file()
        );

        g.teardown().unwrap();

        let restored = fs::symlink_metadata(resolv_conf(&rootfs)).unwrap();
        assert!(restored.file_type().is_symlink(), "original was not restored as a symlink");
        assert_eq!(
            fs::read_link(resolv_conf(&rootfs))
                .unwrap()
                .to_str()
                .unwrap(),
            target
        );
    }

    #[test]
    fn teardown_removes_the_temporary_file_when_there_was_no_original() {
        let (_temp, rootfs) = rootfs_with_etc();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        setup_guard(&mut g).unwrap();
        g.teardown().unwrap();

        assert!(!resolv_conf(&rootfs).exists());
    }

    #[test]
    fn a_failed_setup_puts_the_original_back() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let ops = Arc::new(FailFirstWrites::new(LocalRootfsOps::open(&rootfs).unwrap(), 1));
        let mut g = RootfsResolvConf::new(
            &rootfs,
            Some(generated(&["1.1.1.1"])),
            Utf8Path::new("/etc/resolv.conf"),
            ops,
            false,
        );

        assert!(setup_guard(&mut g).is_err());
        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    // The ENOSPC shape: `take` unlinked the original, then both the install and the
    // rollback failed, so the only copy left is the one the guard holds in memory.
    // Losing it silently is the failure mode being guarded against — the error has to
    // name the detached entry, and the guard has to stay armed so `Drop` retries.
    #[test]
    fn a_failed_rollback_is_reported_and_retried_on_drop() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let ops = Arc::new(FailFirstWrites::new(LocalRootfsOps::open(&rootfs).unwrap(), 2));
        {
            let mut g = RootfsResolvConf::new(
                &rootfs,
                Some(generated(&["1.1.1.1"])),
                Utf8Path::new("/etc/resolv.conf"),
                ops,
                false,
            );

            let err = setup_guard(&mut g).unwrap_err();
            let rendered = format!("{err:#}");
            assert!(rendered.contains("could not be put back"), "unexpected error: {rendered}");
            assert!(rendered.contains("write refused"), "the write error was lost: {rendered}");
            assert!(!resolv_conf(&rootfs).exists(), "the entry should still be detached");
        }

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    #[test]
    fn setup_refuses_a_symlinked_etc() {
        let (_temp, rootfs) = rootfs_with_etc();
        let outside = rootfs.join("outside");
        fs::create_dir(&outside).unwrap();
        fs::remove_dir(rootfs.join("etc")).unwrap();
        std::os::unix::fs::symlink(&outside, rootfs.join("etc")).unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        let err = setup_guard(&mut g).unwrap_err();

        assert!(err.to_string().contains("symlink"), "unexpected error: {err}");
        assert!(!outside.join("resolv.conf").exists(), "wrote through the symlink");
    }

    #[test]
    fn setup_errors_when_etc_is_missing() {
        let temp = tempfile::tempdir().unwrap();
        let rootfs = Utf8PathBuf::from_path_buf(temp.path().to_path_buf()).unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        assert!(setup_guard(&mut g).is_err());
    }

    #[test]
    fn drop_restores_the_original_when_teardown_was_not_called() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        {
            let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
            setup_guard(&mut g).unwrap();
        }

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "original\n");
    }

    #[test]
    fn teardown_is_idempotent() {
        let (_temp, rootfs) = rootfs_with_etc();
        fs::write(resolv_conf(&rootfs), "original\n").unwrap();

        let mut g = guard(&rootfs, Some(generated(&["1.1.1.1"])));
        setup_guard(&mut g).unwrap();
        g.teardown().unwrap();
        fs::write(resolv_conf(&rootfs), "written after teardown\n").unwrap();
        g.teardown().unwrap();

        assert_eq!(fs::read_to_string(resolv_conf(&rootfs)).unwrap(), "written after teardown\n");
    }
}
