---
name: CI
on:
  push:
    branches:
    - main
  pull_request:
permissions: {}
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build test
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Lint with clippy
      run: cargo clippy --all-targets --all-features
    - name: Check formatting
      run: cargo fmt --all --check
