---
name: CI
on:
  push:
    branches:
    - main
  pull_request:
permissions: {}
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        target:
        - 'x86_64-unknown-linux-gnu'
        - 'aarch64-unknown-linux-gnu'
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup Aqua
      uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.50.0
    - name: Cache cargo registry
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Check formatting
      run: cargo fmt --all --check
    - name: Lint with clippy
      run: cargo clippy --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose
    - name: Add Target
      run: rustup target add ${{ matrix.target }}
    - name: Build release
      run: cargo zigbuild --release --verbose --target=${{ matrix.target }}.2.17
