---
name: CI
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
permissions: {}
jobs:
  ##############################################################################
  # Format
  ##############################################################################
  format:
    name: Format
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: read
    uses: ./.github/workflows/wc-format.yml
  ##############################################################################
  # Reviewdog
  ##############################################################################
  reviewdog:
    name: Reviewdog
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    permissions:
      actions: read
      checks: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/wc-reviewdog.yml
  ##############################################################################
  # Fetch
  ##############################################################################
  fetch:
    name: Fetch
    permissions:
      contents: read
    uses: ./.github/workflows/wc-fetch.yml
  ##############################################################################
  # Test
  ##############################################################################
  test:
    needs:
    - fetch
    name: Test
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: read
    uses: ./.github/workflows/wc-test.yml
  ##############################################################################
  # Build
  ##############################################################################
  build:
    needs:
    - fetch
    name: Build
    permissions:
      contents: read
      id-token: write
      attestations: write
    uses: ./.github/workflows/wc-build.yml
  ##############################################################################
  # Release
  ##############################################################################
  release:
    needs:
    - build
    name: Release
    permissions:
      contents: write
    uses: ./.github/workflows/wc-release.yml
  ##############################################################################
  # Status Check
  ##############################################################################
  ci:
    needs:
    - format
    - reviewdog
    - fetch
    - test
    - build
    - release
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: ${{ failure() || cancelled() }}
    steps:
    - name: Failure Status
      run: exit 1
