---
name: CI
on:
  push:
    branches:
    - main
  pull_request:
permissions: {}
jobs:
  ##############################################################################
  # Test
  ##############################################################################
  test:
    name: Test
    permissions:
      contents: read
    uses: ./.github/workflows/wc-test.yml
  ##############################################################################
  # Build
  ##############################################################################
  build:
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/wc-build.yml
  ##############################################################################
  # Status Check
  ##############################################################################
  ci:
    needs:
    - test
    - build
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: ${{ failure() || cancelled() }}
    steps:
    - name: Failure Status
      run: exit 1
