---
name: Autofix
on:
  workflow_call:
permissions: {}
concurrency:
  group: autofix-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  autofix:
    name: AutoFix
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup Aqua
      uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.50.0
    - name: Formatting
      run: task format
    - name: Autofix
      uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944 # v1.3.1
