---
name: Test
on:
  workflow_call:
permissions: {}
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
      with:
        aqua_version: v2.62.0
    - name: Restore cargo deps cache
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        key: deps-${{ hashFiles('**/Cargo.lock') }}
        path: ~/.cargo/registry/
    - name: Restore test cache
      id: test-cache-restore
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        key: test-${{ hashFiles('**/Cargo.lock') }}
        path: target/
    - name: Setup test
      run: |-
        task setup:test
    - name: Test
      run: |-
        task test
    - name: Save test cache
      if: github.ref == 'refs/heads/main' && steps.test-cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        key: ${{ steps.test-cache-restore.outputs.cache-primary-key }}
        path: target/
